apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:  # setup code sync
    - image: ikechukwu1903/auth
      context: auth  # Folder that contains the image
      docker:
        dockerfile: Dockerfile
      sync:  
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: ikechukwu1903/client
      context: client  # Folder that contains the image
      docker:
        dockerfile: Dockerfile
      sync:  
        manual:
          - dest: .
            src: '**/*.js'
    - image: ikechukwu1903/tickets
      context: tickets  # Folder that contains the image
      docker:
        dockerfile: Dockerfile
      sync:  
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: ikechukwu1903/orders
      context: orders  # Folder that contains the image
      docker:
        dockerfile: Dockerfile
      sync:  
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: ikechukwu1903/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: ikechukwu1903/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
