apiVersion: v1
kind: Secret
metadata:
  name: mysecrets
type: Opaque
data:
  jwt-secret: Ym9tYm9jbGFwX2JhYmFyYW50YW4=
  stripe-secret: c2tfdGVzdF81MUx1MUwzS1dkRXNjWnJaUU4yOThGeGpwRFB2TE1JOE5NaFZSQnowZkFCdFRZdXRhM1BxV1drZW56UlZkeElxNEFPellkZzVTUldNSkhHcnB2YXFjaHpQTjAwZ1o5YlhWTlc=
  # stripe-secret: sk_test_51Lu1L3KWdEscZrZQN298FxjpDPvLMI8NMhVRBz0fABtTYuta3PqWWkenzRVdxIq4AOzYdg5SRWMJHGrpvaqchzPN00gZ9bXVNW

