name: tests-payments

on:
  pull_request:

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: "Payment service"
        uses: actions/checkout@v2
        run: cd payments && npm install && npm run test:ci
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      # - uses: actions/checkout@v2
      # - run: cd payments && npm install && npm run test:ci
