name: tests-payments

on:
  pull_request:

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: "Payment service"
        uses: actions/checkout@v2
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      - run: cd payments && npm install
      - run: npm run test:ci
